version: "3.9"

services:
  - name: ttn-app
    dockerfile: Dockerfile
    env:
      - key: PG_USER
        value: hakkarian
      - key: PG_PASSWORD
        value: 1234
      - key: PG_HOST
        value: ttn_db
      - key: PG_DB
        value: ttn_live_db
    envFromSecret:
      - secretName: ttn-app-secrets
    ports:
      - port: 3000
        servicePort: 3000
    volumes:
      - name: ttn-app-volume
        mountPath: /app

  - name: ttn-db
    dockerfile: Dockerfile
    env:
      - key: POSTGRES_PASSWORD
        value: 1234
      - key: POSTGRES_DB
        value: ttn_live_db
      - key: POSTGRES_USER
        value: hakkarian
    ports:
      - port: 5432
        servicePort: 5432
    volumes:
      - name: ttn-db-data
        mountPath: /var/lib/postgresql/data

volumes:
  - name: ttn-app-volume
  - name: ttn-db-data