services:
    type: web 
  - name: ttn-app-backend
    env: node
    repo: https://github.com/hakkarian/ttn-app-backend.git
    region: oregon
    branch: main
  - buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: .9.0
      - key: NODE_ENV
        value: production